config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "pages#home"
  get "about", to: 'pages#about'
  resources :articles
  get 'signup', to: 'users#new'  # need to create user contriller and action new in it
  # post 'users', to: 'users#create' # users will have all restful routes as well, for that resources is used
  resources :users, except: [:new]  # we get all routes except new

  get 'login', to: 'sessions#new'  # won't use resources because login does not hit database 
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :categories, except: [:destroy]
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    has_many :article_categories
    has_many :categories, through: :article_categories
    validates :title, presence: true, length: { minimum: 4, maximum: 15 } 
    validates :description, presence: true
    
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController 
    # all before action methods must follow certain order depending on flow to work properly
    before_action :set_article, only: [:show, :edit, :update, :destroy]
    before_action :require_user, except: [:show, :index] # requires user for certain actions(edit,new,destroy)
    before_action :require_same_user, only: [:edit, :update, :destroy] # to check current user wrt article user for edit 
    # it is helper which will run set_aricle method before we do any action mentioned in only
    # if only is not used it will apply to every actions which we don't want
    def show
        # byebug                               # for @article set_article -> private method is used
        # @article = Article.find(params[:id])   # @article -> instance variable to access in webpage  
    end 

    def index 
        @articles = Article.all             # @articles -> all articles named according to convention
    end 

    def new
        @article = Article.new
    end 
    # new and create action both acts upon new.html.erb
    # new action gives page new.html.erb with GET
    # create action post the new data to new.html.erb with POST 

    def edit            # for @article set_article -> private method is used
        # @article = Article.find(params[:id])  # it will find article of specific index and shows to page
        @article.user = User.first  
    end

    def create 
        @article = Article.new(article_params)  # article_pramas -> private method to reduce redundancy
        @article.user = current_user  # current_user is a helper method which gives current signed in user   
        if @article.save 
            flash[:notice] = "Article is saved successfully"
            redirect_to @article  # goes to  articles/:id - it is another way of returning to route 
        else  
            render 'new'   # if article is not saved it will redirect to articles/new
        end
    end
    
    # update and edit both acts upon edit.html
    # edit action gives page edit.html.erb with GET
    # update actiion post data to edit.html.erb with POST
    def update 
        # byebug
        # @article = Article.find(params[:id])    # instead set_article -> private method is used
        # if @article.update(params.require(:article).permit(:title, :description))
        if @article.update(article_params)  
            flash[:notice] = "Article is updated successfully"
            redirect_to @article 
        else 
            render 'edit'
        end
    end 

    def destroy
        # @article = Article.find(params[:id])  # instead set_article -> private method is used
        @article.destroy
        redirect_to articles_path   # it will go to index page  /articles
    end 

    # to avoid redunduncy of code we will define some code that can be used again
    private   # it means everyting define below is private attribute and can call only in this class
    def set_article  # this method will find article and set it as instance variable    
        @article = Article.find(params[:id])
    end

    def article_params
        params.require(:article).permit(:title, :description, category_ids: [])
    end

    def require_same_user   # when current user is not article's user and current is not admin
        if current_user != @article.user && !current_user.admin?
            flash[:alert] = "You can only edit or delete your own aticle"
            redirect_to @article 
        end
    end 
    # private doesn't need end block
end 

app/views/articles/_article.html.erb
<div class="container">
  <% @articles.each do |article| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            <% if article.user %>
              by <%= link_to article.user.username, user_path(article.user) %>
            <% end %>
          </div>
          <div class="card-body">
            <h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-success" %></h5>
            <p class="card-text"><%= truncate(article.description, length: 100) %></p>

            <%= link_to "View", article_path(article), class: "btn btn-outline-success" %>
            
            <% if logged_in? && (article.user == current_user || current_user.admin?) %>
                <%= link_to "Edit", edit_article_path(article), class: "btn btn-outline-info" %>
                <%= link_to "Delete", article_path(article), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(article.created_at) %> ago, 
            edited <%= time_ago_in_words(article.updated_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/articles/_form.html.erb
<div class="container">  <%# Same form is used for both edit and create #%>
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj: @article %>
      <%= form_with(model: @article, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :title, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Title of article" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :description, class: "col-2 col-form-label text-light" %>
          <div class="col-10"> 
            <%= f.text_area :description, rows: 10, class: "form-control shadow rounded", placeholder: "Description of article" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :category, class: "col-2 col-form-label text-light" %>
          <div class="col-10"> 
            <%= f.collection_select(:category_ids, Category.all, :id, :name,
             {prompt: "make your selection from list below(can be empty)"}, {multiple: true}  )  %>
          </div>
        </div>

        <div class="form-group row justify-content-center">
          <%= f.submit class: "btn btn-outline-light btn-lg" %>
        </div>
      <% end %>
    </div>
    <div class="mb-3">
      <%= link_to '[ Cancel and return to articles listing ]', articles_path, class: "text-info" %>
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<h1 class="text-center mt-4">Edit article</h1>
<%= render 'form' %>

<!--
<%if @article.errors.any?%>
<h3> The following errors are prevented from article being saved</h3>
<ul>
    <% @article.errors.full_messages.each do |msg|%>
    <li> <%= msg %> </li>
    <% end %>
</ul>
<%end%>


<%= form_with(model: @article, local: true) do |f|%>  
                                         <%#we have to submit this to update action -  /articles/:id #%>

<p>
    <%= f.label :title%> <br>
    <%= f.text_field :title%>
</p>

<p>
    <%= f.label :description%> <br>
    <%= f.text_area :description%>
</p>

<p>
    <%= f.submit%>
</p>

<% end %> 
<%= link_to "Cancel and return to Articles Listing", articles_path%>

-->

app/views/articles/index.html.erb
<h1 class="text-center mt-4">Listing all articles</h1>
<%= render 'article' %>


<!-- 
<table>
    <thead>
        <tr>
            <th>Title </th>
            <th>Description </th>
            <th colspan="3">Action </th><%#colspan-to merge last 3 columns; or we can add all in single <td>#%>
        </tr>
    </thead>
    <tbody>
        <% @articles.each do |article| %>
        <tr>            
        <td><%= article.title %> </td>
        <td><%= article.description %> </td>  
        <td><%= link_to 'Show', article_path(article)%> </td>
        <td><%= link_to 'Edit', edit_article_path(article)%></td>        <%#data:...-> Javascript syntax #%>
        <td><%= link_to 'Delete', article_path(article), method: :delete, data: {confirm: "Are you sure?"} %></td>              
        </tr>   <%# here we are adding :method because show & delete routes are same ie.  /article/:id #%>
        <%end%>
    </tbody>
</table>
-->
<%= link_to "Create Aticle", new_article_path(@article)%>

app/views/articles/new.html.erb
<h1 class="text-center mt-4">Create a new article</h1>
<%= render 'form' %>

<!--
<div id="page-content">
    <h2 class="text-center mt-4"> Create a new article </h2>
    <%= render 'form' %>

    <%if @article.errors.any?%>
    <h3> The following errors are prevented from article being saved</h3>
    <ul>
        <% @article.errors.full_messages.each do |msg|%>
        <li> <%= msg %> </li>
        <% end %>
    </ul>
    <%end%>

    <%= form_with scope: :article, url: articles_path, local: true do |f|%>
        <div class="form-group-row">
            <%= f.label :title, class: "col-2 col-form-label"%> 
            <div class="col-10" >
                <%= f.text_field :title%>
            </div>
        </div>

        <div class="form-group-row">
            <%= f.label :description, class: "col-2 col-form-label"%>
            <div class="col-10" >
                <%= f.text_area :description%>
            </div>
        </div>

    <p>
        <%= f.submit%>
    </p>

    <% end %>   


    <%= link_to "Return to Articles Listing", articles_path%>

</div>
-->

app/views/articles/show.html.erb
<h3> Showing Article Information</h3>   

<p> <strong>Title: </strong><%= @article.title%> </p>
<p> <strong>Description: </strong><%= @article.description%> </p>
 by <%= @article.user.username if @article.user%>
<p><%= link_to "Edit Article", edit_article_path%> |
<%= link_to "Delete Article", article_path, method: :delete, data: {confirm: "Are you sure"}%> |
<%= link_to "Return to Articles Listing", articles_path%>
</p>