config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "pages#home"
  get "about", to: 'pages#about'
  resources :articles
  get 'signup', to: 'users#new'  # need to create user contriller and action new in it
  # post 'users', to: 'users#create' # users will have all restful routes as well, for that resources is used
  resources :users, except: [:new]  # we get all routes except new

  get 'login', to: 'sessions#new'  # won't use resources because login does not hit database 
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :categories, except: [:destroy]
end

app/views/pages/about.html.erb
<h3> This is ABOUT page </h3>
<p><%= link_to "Home", root_path%> </p>
<p><%= link_to "Articles", articles_path%> </p>

app/views/pages/home.html.erb
<h3> This is home page </h3> 
<!-- <p><%= link_to "About", about_path%> |
    <%= link_to "click for articles", articles_path%>  </p> -->

<div class="container" id='home-container'> 
    <div id='page-content'> 
        <div class="jumbotron text-center text-white">
        <h1 class="display-4">Dummy Project!</h1>
        <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
        <hr class="my-4">
        <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
        <!--<a class="btn btn-success btn-lg" href="#" role="button">Sign up!</a>-->
        <%= link_to "Sign up!", signup_path, class: "btn btn-success btn-lg"%>
        </div>
    </div>
</div>

<footer id="sticky-footer" class="flex-shrink-0 py-4 bg-dark text-white">
    <div class="container text-center">
      <small>Copyright &copy; Your Website</small>
    </div>
</footer>
                                                                                