config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "pages#home"
  get "about", to: 'pages#about'
  resources :articles
  get 'signup', to: 'users#new'  # need to create user contriller and action new in it
  # post 'users', to: 'users#create' # users will have all restful routes as well, for that resources is used
  resources :users, except: [:new]  # we get all routes except new

  get 'login', to: 'sessions#new'  # won't use resources because login does not hit database 
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :categories, except: [:destroy]
end

app/models/category.rb
class Category < ApplicationRecord 
    validates :name, presence: true, length: { minimum: 3, maximum: 25}
    validates_uniqueness_of :name 
    has_many :article_categories  
    has_many :articles, through: :article_categories
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :require_admin, except: [:index, :show]  # restricting new to only admin users

    def new 
        @category = Category.new
    end 

    def create          # should not create category if not admin user
        @category = Category.new(params.require(:category).permit(:name) )
        if @category.save 
            flash[:notice] = "category successfully created"
            redirect_to @category   # show page  localhost:3000/categories/id
        else 
            render 'new'           # new page   localhost:3000/categories/new
        end 
    end 

    def index 
        @categories = Category.all
    end 

    def show 
    
    end 

    private 

    def require_admin
        if !(logged_in? && current_user.admin?)  # if not logged in and current user is not admin
            flash[:alert] = "only admin logged in users  can perform this action"
            redirect_to categories_path
        end 
    end 
end

app/views/categories/index.html.erb
<h1 class="text-center mt-4">Categories</h1>
<div class="container">
  <% @categories.each do |category| %>
    <div class="row justify-content-md-center">
      <div class="col-4 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          
           <div class="card-body">
            <h5 class="card-title"><%= link_to category.name, category_path(category), class: "text-success" %></h5>
           </div>
            <div class="card-footer text-muted">
                <small>Created <%= time_ago_in_words(category.created_at) %> ago, 
                edited <%= time_ago_in_words(category.updated_at) %> ago</small>
            </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/categories/new.html.erb
<h1 class="text-center mt-4"> Create a new Category </h1>

<!--This is from form partial to new -->
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">

      <%= render 'shared/errors', obj: @category %>

      <%= form_with(model: @category, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :name, "Category Name", class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Enter category name" %>
          </div>
        </div>

        <div class="form-group row justify-content-center">
          <%= f.submit class: "btn btn-outline-light btn-lg" %>
        </div>    
      <% end %>
    </div>
    <div class="mb-3">
      <%= link_to '[ Cancel and return t    o articles listing ]', articles_path, class: "text-info" %>
    </div>
  </div>
</div> 