config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "pages#home"
  get "about", to: 'pages#about'
  resources :articles
  get 'signup', to: 'users#new'  # need to create user contriller and action new in it
  # post 'users', to: 'users#create' # users will have all restful routes as well, for that resources is used
  resources :users, except: [:new]  # we get all routes except new

  get 'login', to: 'sessions#new'  # won't use resources because login does not hit database 
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :categories, except: [:destroy]
end

app/views/layouts/_messages.html.erb
  <% flash.each do |name, msg| %>
    <%= msg %>
    <%# <%= name #%>    <%# here name is :notice form articles_controller action#%>
  <% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <!--<<a> class="navbar-brand" id="logo" href="#">Dummy Project</a>-->
    <%=link_to "Dummy Project", root_path, class: "navbar-brand", id: "logo"%>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
            <li class="nav-item">
                <%= link_to "Users", users_path, class: "nav-link"%>
            </li>
            <li class="nav-item active">
                <!--<a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>-->
                <%= link_to "Articles", articles_path, class: "nav-link"%>
            </li>
            <li class="nav-item">
                <!--<a class="nav-link" href="#">Features</a>-->
                <%= link_to "Create Aticle", new_article_path(@article), class: "nav-link"%>
            </li>
            
            <%if logged_in?%>
                <li class="nav-item">
                    <%= link_to current_user.username, user_path(current_user), class: "nav-link"%>
                </li>
                <li class="nav-item">
                    <%= link_to "Logout", logout_path, class: "nav-link", method: :delete%>
                </li>
                
            <%else%>
                <li class="nav-item">
                    <%= link_to "Log in", login_path, class: "nav-link"%>
                </li>
                <li class="nav-item">
                    <%= link_to "Sign up", signup_path, class: "nav-link"%>
                </li>
            <%end%>

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Categories
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <% if logged_in? && current_user.admin? %>
                    <%= link_to "Create new category", new_category_path, class: "dropdown-item" %>
                <% end %>  
                <%= link_to "View categories", categories_path, class: "dropdown-item" %>
                </div>
            </li>

            <% if logged_in? %>
                <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                     <%="Admin" if current_user.admin?%>Profile (<%=current_user.username%>)
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <%= link_to "View your profile", user_path(current_user), class: "dropdown-item" %>
                    <%= link_to "Edit your profile", edit_user_path(current_user), class: "dropdown-item" %>
                    <%= link_to "Delete profile", user_path(current_user), class: "dropdown-item text-danger", method: :delete, data: { confirm: "Are you sure?" } %> 
                </div>
                </li>
            <% end %>

            

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Dropdown link
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <a class="dropdown-item" href="#">Something else here</a>
                </div>
            </li>
        </ul>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DummyProj</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>